name: Publish PPA

on:
  release:
    types: [published]

jobs:
  publish-ppa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run publish-ppa.sh script
        run: ./publish-ppa.sh
